language: python
env:
- DATABASE_URL=postgresql://localhost/travis_ci_test
services:
- postgresql
branches:
  only: final
python:
- '3.6'
install:
- pip install -r requirements-travis.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python create_db_only.py
script:
- coverage run --source=app tests.py
after_success:
- coverage report
deploy:
  provider: heroku
  api_key:
    secure: KVdmjRFF4hK9xKjH3YUy1191ZxgtAcmj35fOMOpoirvQLA45eqb7qRu8NrqWRXj73eCnjbJc/rjYAF5UU2eMnVX14jtfPQucbHiMoPuhqkZbIlGTHkptMQpx1V81rRqlk6xhDZlLL82r9PnGn8drHhjG3r7pJ/k2B3rs8Yt/CvGMWBkO2L02zRhbBmxa1kLy053TfwxjqV2xUPKszL4ruGiP1WfYaW2PckukHgLgoNTGPC+9rbnF7lsl2JTjUZniaplx9vmMMVrThcYfYQ0GDYHOjJ+SzMUxx7aSepqPHJV1x7aWKgK4e0TKN6r76aZkI9ffMlggxzWdlgAX+1yAhE2GbxgmL1NK9Ag4IM+B7UCE2/LYRhJAtNxvaaxZJpaNW5bEN1ilDWRw39uzzZxdlFMK7Abifzc2gazj9ZbR1k7ypC9uugwR/aL+MALN9KpU2NPNUj7xgQs0VvyplE3MbfGD9OW9JafhvtFKJstycp0dZ/8nHSrfS2KsfEkBn+GWNx/k7ACfdRAMy/xKZqESIL8iJiwjtQecn2BNBYlHbv8nOuhy/0g8Fm6LVXDEB5i3159V9lRfuR36UFBGGH4xvbmQBhZnVlOzz3N0dhZnO+IB8cF7cGWowHH9jV3vD/uVCoUA+fdEiOw4dSrW2AhBBJub9gGo2bhTxmfesG72kDY=
  app: jackal-flask
  on:
    repo: wgx731/jackal-flask
    branch: final
